### ISSUE TITLE
Translating & Unknown "bug"

### ISSUE THREAD

**Issue by RedyHUN** [Plugineers/Advanced-Portals#120]
Hey! I just have 3 thing to say.
Your plugin is really good. but,
can you please add a Translating options to the messages please.
and can you tell me what is this:
https://pastebin.com/nskSfzWw
I just typed: "/portal create name:endth triggerBlock:Water desti:teaház"
Good luck fixing the bugs and adding the Translating option! ;)

**Comment by sekwah41** [comment]
Translate option is already finished for the recoded system and I am unsure if you are saying there is an issue or just the command line messages (they were a debugging piece of info I forgot to remove tho havent pushed the latest update to spigot.
