### ISSUE TITLE
Can’t seem to rotate nether portal block

### ISSUE THREAD

**Issue by mdswente** [Plugineers/Advanced-Portals#124]
What am I doing wrong? Crouch click?

**Comment by sekwah41** [comment]
I noticed this the other week but I have been busy fixing some other issues on another project. I am not 100% sure what type of block a portal block gets its rotation data from as there are like 3 different types and it was being a bit fiddly. I will search later and try to do some fixes while on the train :)

**Comment by sekwah41** [comment]
Fixed in release https://github.com/Plugineers/Advanced-Portals/releases/tag/0.0.45
