### ISSUE TITLE
Version of server with the plugin

### ISSUE THREAD

**Issue by NoopyyGaming** [Plugineers/Advanced-Portals#128]
The plugin is not supported with the 1.9.4 version : 

![bug](https://user-images.githubusercontent.com/33123515/44944230-7c4e2180-add3-11e8-8e2e-4127c5dae27d.PNG)

**Comment by sekwah41** [comment]
You need to use the one specifically listed for 1.12 and below

**Comment by sekwah41** [comment]
You can download it here https://github.com/Plugineers/Advanced-Portals/releases/tag/0.0.41
